### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bjohnsto**

### CODE REVIEW

**Review by jochapma — CHANGES_REQUESTED** [review]
This seems a little informal for a humorless professional development organization like ours.

**Comment by bjohnsto** [comment]
How about if I say "kind of" instead of kinda?

**Comment by bjohnsto** [comment]
> This seems a little informal for a humorless professional development organization like ours.

How about I say "kind of" instead of kinda

**Comment by jochapma** [comment]
Excellent, dude (I mean, esteemed fellow developer).

**Review by jochapma — APPROVED** [review]

**Pull request merged**
